// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgEdf7W0t-VaXtLaEwDIQjD_iFY5dCK4',
    appId: '1:767694513954:web:39b67ba698969e5d2c277b',
    messagingSenderId: '767694513954',
    projectId: 'flutter-test-ca8f4',
    authDomain: 'flutter-test-ca8f4.firebaseapp.com',
    storageBucket: 'flutter-test-ca8f4.firebasestorage.app',
    measurementId: 'G-TM002RZZDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmsFvPtwCRPYZwK23C7lJm_UugNVvAB3k',
    appId: '1:767694513954:android:a1c0259ee042ca4a2c277b',
    messagingSenderId: '767694513954',
    projectId: 'flutter-test-ca8f4',
    storageBucket: 'flutter-test-ca8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvb4N1e7CMgG_PKQmv9OUJrw9ktzR5UUc',
    appId: '1:767694513954:ios:9a73353238fafa102c277b',
    messagingSenderId: '767694513954',
    projectId: 'flutter-test-ca8f4',
    storageBucket: 'flutter-test-ca8f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiToolkitExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvb4N1e7CMgG_PKQmv9OUJrw9ktzR5UUc',
    appId: '1:767694513954:ios:9a73353238fafa102c277b',
    messagingSenderId: '767694513954',
    projectId: 'flutter-test-ca8f4',
    storageBucket: 'flutter-test-ca8f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiToolkitExample',
  );
}
